Update installation guide
dojot/docs pull request #105
Opened 2020-11-05 16:56 UTC by LeonardoMariano

The dojot installation guide (for both docker-compose and k8s) has been updated to meet the needs of version v0.5.0

2020-11-05 17:17 UTC, mprevide requested changes
You also need to translate to pt-br.

2020-11-06 16:29 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/installation-guide.po
> +msgstr ""
MIssing translation

2020-11-06 16:29 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/installation-guide.po
> +msgstr ""
MIssing translation

2020-11-06 16:29 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/installation-guide.po
> +msgstr ""
MIssing translation

2020-11-06 16:29 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/installation-guide.po
>  msgstr ""
MIssing translation

2020-11-06 16:29 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/installation-guide.po
>  msgstr ""
MIssing translation

2020-11-06 18:30 UTC, mprevide approved these changes
Great :1st_place_medal:

2020-11-09 11:16 UTC, mprevide commented
Do you see me suggestions https://github.com/dojot/dojot/issues/1473?

2020-11-10 12:39 UTC, andersonluisribeiro requested changes

2020-11-10 12:39 UTC, andersonluisribeiro commented on source/installation-guide.rst
> +The volumes of microservices that Dojot uses are incompatible between dojot versions. This means
I think they "can be" incompatible

2020-11-10 14:41 UTC, andersonluisribeiro approved these changes
:+1:

2020-11-10 15:40 UTC, mprevide approved these changes

2020-11-10 16:26 UTC, merged