Dashboard
dojot/docs pull request #106
Opened 2020-11-11 16:48 UTC by wellitonSouza

2020-11-11 17:29 UTC, thiagodpf approved these changes

2020-11-12 12:49 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/components-and-apis.po
> +msgstr "Endpoints expostos"
Put between `*` when is using a  english word in a pt traslantion.

2020-11-12 12:50 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/components-and-apis.po
> +msgstr ""
Add translation

2020-11-12 12:50 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/components-and-apis.po
> +msgstr ""
Add translation

2020-11-12 12:50 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/components-and-apis.po
> +msgstr ""
Add translation

2020-11-12 12:52 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/using-web-interface.po
> +"add new features. dojot currently supports the firmware upgrade procedure"
`Dojot` instead of `dojot`

2020-11-12 12:53 UTC, mprevide commented on source/using-web-interface.rst
> +dojot currently supports the firmware upgrade procedure via the LwM2M communication protocol. For details regarding the procedure for integrating with your device please check the LwM2M protocol spec
Dojot

2020-11-12 12:53 UTC, mprevide requested changes
I left a few comments

2020-11-12 13:17 UTC, wellitonSouza commented on source/using-web-interface.rst
> +dojot currently supports the firmware upgrade procedure via the LwM2M communication protocol. For details regarding the procedure for integrating with your device please check the LwM2M protocol spec
I did as requested changes

2020-11-12 13:52 UTC, mprevide approved these changes

2020-11-13 11:39 UTC, thiagodpf approved these changes

2020-11-13 12:23 UTC, merged