V0.5.0 new
dojot/docs pull request #117
Opened 2021-01-18 14:29 UTC by marciofunes

Hello, PR with some PO reviews and corrections :D

2021-01-18 14:43 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/installation-guide.po
> +msgstr "Clique aqui para acessar o guia de instalação da dojot com kubernetes"
Missing link in translation

2021-01-18 14:43 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/load-testing-dojot-platform.po
> +#, fuzzy
Resolve fuzzy

2021-01-18 14:45 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/faq.po
> +#, fuzzy
Resolve fuzzy

2021-01-18 14:46 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/using-web-interface.po
> +#, fuzzy
Resolve fuzzy

2021-01-18 14:46 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/using-web-interface.po
> +#, fuzzy
Resoslve fuzzy

2021-01-18 14:46 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/using-web-interface.po
> +#, fuzzy
Resolve fuzzy

2021-01-18 14:46 UTC, mprevide commented on source/locale/pt_BR/LC_MESSAGES/using-web-interface.po
> +#, fuzzy
Resolve fuzzy

2021-01-18 14:47 UTC, mprevide requested changes
I left some comments.
Please always check if there are fuzzies

2021-01-18 14:47 UTC, mprevide commented
There is a conflict, check that

2021-01-18 15:04 UTC, marciofunes commented on source/locale/pt_BR/LC_MESSAGES/load-testing-dojot-platform.po
> +#, fuzzy
Done

2021-01-18 15:04 UTC, marciofunes commented on source/locale/pt_BR/LC_MESSAGES/faq.po
> +#, fuzzy
Done

2021-01-18 15:04 UTC, marciofunes commented on source/locale/pt_BR/LC_MESSAGES/using-web-interface.po
> +#, fuzzy
Done

2021-01-18 15:04 UTC, marciofunes commented on source/locale/pt_BR/LC_MESSAGES/using-web-interface.po
> +#, fuzzy
Done

2021-01-18 15:04 UTC, marciofunes commented on source/locale/pt_BR/LC_MESSAGES/using-web-interface.po
> +#, fuzzy
Done

2021-01-18 15:04 UTC, marciofunes commented on source/locale/pt_BR/LC_MESSAGES/using-web-interface.po
> +#, fuzzy
Done

2021-01-18 16:08 UTC, mprevide commented
There is more conflits...

2021-01-18 16:09 UTC, mprevide commented
I think You should create a branch based in release/v0.5.1 and add just the new changes

2021-01-19 00:11 UTC, mprevide commented
Or you can create this pr to release/v0.5.2, but doesnt forget about using the right base.

2021-01-20 18:16 UTC, mprevide commented
Please, refer a issue in this PR

2021-01-28 16:44 UTC, closed without merging