Bump to v0.8.0
dojot/docs pull request #145
Opened 2022-09-30 17:44 UTC by danielapetito

2022-09-30 18:20 UTC, marianoleonardo requested changes
Deixei alguns comentários!

2022-09-30 18:20 UTC, marianoleonardo commented on source/components-and-apis.rst
> +.. _API - InfluxDB-Retriever: https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.8.0
Agora que percebi que ficou faltando adicionar nesse arquivo a API do file-mgmt

Adicione no final do arquivo seguindo os padrões do mesmo:
```
https://dojot.github.io/dojot/storage/file/minio/file-mgmt/doc.html?version=v0.8.0
```

2022-09-30 18:20 UTC, marianoleonardo commented on source/installation-guide.rst
> +In this video tutorial above, version v0.8.0 is used, but the same video
Nesse linha a versão deveria ser mantida `v0.7.1` visto que é a versão presente no vídeo.

2022-09-30 18:20 UTC, marianoleonardo commented on source/installation-guide.rst
> +In this video tutorial above, version v0.8.0 is used, but the same video
Nesse linha a versão deveria ser mantida `v0.7.1` visto que é a versão presente no vídeo.

2022-09-30 18:20 UTC, marianoleonardo commented on source/locale/pt_BR/LC_MESSAGES/installation-guide.po
> +"In this video tutorial above, version v0.8.0 is used, but the same video "
Nesse linha a versão deveria ser mantida `v0.7.1` visto que é a versão presente no vídeo.

2022-09-30 18:20 UTC, marianoleonardo commented on source/locale/pt_BR/LC_MESSAGES/installation-guide.po
> +"Nesse tutorial acima, a versão utilizada foi a v0.8.0, mas o mesmo video "
Nesse linha a versão deveria ser mantida `v0.7.1` visto que é a versão presente no vídeo.

2022-09-30 18:20 UTC, marianoleonardo commented on source/locale/pt_BR/LC_MESSAGES/releases.po
> +msgstr "O serviço de autenticação básica é responsável por gerar credenciais para "
Acho que na tradução, podemos manter o nome do serviço como `basic-auth` ao invés de traduzi-lo.

2022-09-30 18:20 UTC, marianoleonardo commented on source/locale/pt_BR/LC_MESSAGES/releases.po
> +msgstr "O gerenciamento de arquivos é responsável por gerenciar os recursos do MinIO na "
Acho que na tradução, podemos manter o nome do serviço como `file management` ao invés de traduzi-lo.

2022-09-30 18:20 UTC, marianoleonardo commented on source/locale/pt_BR/LC_MESSAGES/releases.po
> +msgstr "Histórico de lançamento"
Acho que como estamos falando do serviço `History`, ele não deveria ser traduzido

2022-09-30 18:20 UTC, marianoleonardo commented on source/locale/pt_BR/LC_MESSAGES/releases.po
> +
Apagar essas linhas a mais

2022-09-30 18:35 UTC, marianoleonardo commented
É necessário também atualizar o Guia de Instalação da dojot no kubernetes, adicionando o PDF da versão 0.8.0

2022-09-30 19:17 UTC, danielapetito commented on source/components-and-apis.rst
> +.. _API - InfluxDB-Retriever: https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.8.0
ok

2022-09-30 19:38 UTC, gabrielifg submitted a review, later dismissed
Bom trabalho !!!

2022-09-30 22:43 UTC, gabrielifg approved these changes
👏👏👏

2022-10-03 11:56 UTC, marianoleonardo approved these changes
Bom trabalho! 👏🏼👏🏼

2022-10-03 11:58 UTC, merged